name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - ./Week4/frontend/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: yarn
          cache-dependency-path: './Week4/frontend/yarn.lock'

      - name: Install dependencies 
        working-directory: ./Week4/frontend/
        run: yarn install

      - name: Start
        working-directory: ./Week4/frontend/
        run: yarn start